### ISSUE TITLE
Expected "golden" test files are not present on hackage.

### ISSUE THREAD

**Issue by alaendle** [nevrome/currycarbon#17]
See https://hackage.haskell.org/package/currycarbon-0.3.0.0/src/ - will disable test execution during stackage build for now.

**Comment by nevrome** [comment]
Ah - I see. Thanks for letting me know. I already worried that this setup might be incompatible with hackage.

Could you make a suggestion what I should do about it? I see the following options:

- Just accept that the tests do not run hackage.
- Remove or outsource the golden tests. Maybe there is a way to only enable them with a specific flag when I call `stack test`?
- Figure out how to include the expected files into the archive I upload to hackage, so that they are available for the tests there.

**Comment by alaendle** [comment]
I believe all three options are somehow valid - at least I believe I have seen all these in the wild - so basically it's up to you to decide. Perfect would be option three since it would enable any user to run your tests; option two, would sit in between - at least enable users to run a subset (don't know if this is meaningful for your project - or if it just creates noise and nobody would run the non-default tests); but also the first and simplest option is viable.

**Comment by nevrome** [comment]
Thank you very much for the explanation!

v0.3.0.0 is borked now and I can not remove it from hackage any more, so I guess it will stay as it is. But I'll think about it, try some things and then submit a new, patched version asap.

**Comment by nevrome** [comment]
Ok - I decided to go for option two, because I fear option three might cause more issues down the line, for example with system-dependent encoding of the golden test CLI output.

For future reference here's what I did: https://github.com/nevrome/currycarbon/commit/9a749bc5766ac07c05bff8655b2f58c5fddb919a

I uploaded a new release to hackage (https://hackage.haskell.org/package/currycarbon-0.3.0.1) and I hope it passes all your tests.
