### ISSUE TITLE
Can't parse lab IDs with parentheses

### ISSUE THREAD

**Issue by joeroe** [nevrome/currycarbon#3]
For example, `Ki(KIEV)-6890`, which, astonishingly, [is a standard lab code](http://radiocarbon.webhost.uits.arizona.edu/sites/default/files/Labs-2021_Jun-08.pdf):

```bash
$ ./currycarbon calibrate -q "(Ki(Kiev)-6890)4070+60"
(line 1, column 10):
unexpected "-"
expecting digit

Usage: currycarbon calibrate [DATES] [-i|--inputFile ARG] [-q|--quickOut] 
                             [--densityFile ARG] [--hdrFile ARG] 
                             [--calCurveSegmentFile ARG] 
                             [--calCurveMatrixFile ARG]
  Simple intercept calibration for one or multiple radiocarbon dates
```

**Comment by nevrome** [comment]
Wow - I should have checked that, I guess, but it's a bit obscure. I fear I can only fix this with a general syntax change. What do you think would be best? Maybe `[test]1000+20`? or `{test}1000+20`? We could also switch to a boring `test,1000,20`, but then the sample ID would be a necessary field and I don't want that. Or maybe this is possible with lookaheads in parsec. Hm. 

I think I will go with `[test]1000+20` for now.

**Comment by nevrome** [comment]
This is implemented in v0.6.0, but a test run already indicated that square brackets may also be commonly used in radiocarbon archives. I consider it an intermediate solution, until I found one that works for most cases.

**Comment by joeroe** [comment]
It's only a matter of time until some one puts a `,` in one, though! But whatever you use for brackets, couldn't you just greedily match what's inside them? E.g. I think regex `^\[(.*)\](\d+)\+(\d+)$` would reliably extract your three fields?

**Comment by nevrome** [comment]
Parsing in Haskell works [a bit differently](https://jakewheat.github.io/intro_to_parsing/) from regular expressions.

Anyway: I decided now to go for the boring, comma separated solution and with [a little help from the internet](https://stackoverflow.com/questions/68282790/parsec-fails-without-error-if-reading-from-file) I created a parser that is hopefully (!) pretty robust in v0.7.0. Additional commas that do not belong should throw a meaningful error. 

I'll close this issue now, because it is fixed. If the parser has other flaws we should address them in another issue. Thanks again for testing this in its early state!
